# This is a basic workflow to help you get started with Actions

name: Sync-Images-to-DockerHub

# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repos 
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Set up Docker Buildx
        run: docker/setup-buildx-action@v2.9.1

      # Runs a set of commands using the runners shell
      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false
      - name: Use Skopeo Tools Sync Image to Docker Hub
        run: |
          #!/usr/bin/env bash
          skopeo copy docker://docker.io/eclipse-temurin:8-jre docker://registry.cn-hangzhou.aliyuncs.com/docker14best/eclipse-temurin:8-jre
